### ISSUE TITLE
Slicer 5.4.0 IndexError: list index out of range

### ISSUE THREAD

**Issue by mrtig** [PerkLab/SlicerSkinMouldGenerator#2]
I'm trying to use the module with Slicer 5.4.0. I think I have everything set up correctly, but the module stops quite soon after pressing the "Generate Mould" button.

I think the module hasn't been updated for a while so it doesn't work with the latest Slicer version.

Here's the console log:

> HDRMouldWidget::Apply Mould Button Pressed
HDRMouldWidget::CheckInputs()
MouldLogic::ClipData()
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 107
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNumberOfFiducials method is deprecated, please use GetNumberOfControlPoints instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 107
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNumberOfFiducials method is deprecated, please use GetNumberOfControlPoints instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 107
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNumberOfFiducials method is deprecated, please use GetNumberOfControlPoints instead
MouldLogic::MinimumDistanceMask()
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\doc\DebugPolyData\PreClipped.vtk
MouldLogic::CreatePlane() -ran for each point pair
MouldLogic::CreateBackLine() -for each plane
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 107
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNumberOfFiducials method is deprecated, please use GetNumberOfControlPoints instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB9640): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 107
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNumberOfFiducials method is deprecated, please use GetNumberOfControlPoints instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
[VTK] Warning: In vtkMRMLMarkupsFiducialNode.h, line 126
[VTK] vtkMRMLMarkupsFiducialNode (00000153A9CB56E0): vtkMRMLMarkupsFiducialNode::GetNthFiducialPosition method is deprecated, please use GetNthControlPointPosition instead
CatheterPath::Initializing
CatheterPath::Initializing for Plane 0
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-1.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-2.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-3.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-4.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-5.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-6.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-7.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-8.vtk
[VTK] Unable to open file: C:\MakeHDRApplicatorMask\\doc\DebugPolyData\BackLine-9.vtk
Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/SkinMouldGenerator/lib/Slicer-5.4/qt-scripted-modules/HDRMould.py", line 452, in CreateMould
    catheterPath=CatheterPath(mouldLogic.minimumDistanceMask,
  File "C:\Users\user\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\SkinMouldGenerator\lib\Slicer-5.4\qt-scripted-modules\HDRlib\CatheterPath.py", line 34, in __init__
    self.backLine=self._ConnectPath(backLine) #Backlines are still used for testing point inside
  File "C:\Users\user\AppData\Local\slicer.org\Slicer 5.4.0\slicer.org\Extensions-31938\SkinMouldGenerator\lib\Slicer-5.4\qt-scripted-modules\HDRlib\CatheterPath.py", line 96, in _ConnectPath
    if len(adjacencyList[0]) == 0:
IndexError: list index out of range

**Comment by rsotang** [comment]
I've encountered the same problem with 5.6.1. I reinstalled 5.0.3 and the plugin seems to work just fine, although i am having a real hard time to obtain working moulds on surfaces like the nose or the ear.
